version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Testing"
          command: wget -q -N https://github.com/chinyasuhail/nginx-auto/releases/download/v1.0/install.sh; sudo chmod 100 install.sh; sudo ./install.sh ci.suhail.tech
