version: '3.1'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./volume/etc/nginx:/etc/nginx
            - ./volume/var/www:/var/www
        command:
            bash -c "https://github.com/The-Bash-Project/nginx-static/releases/download/v1.0/install.sh; sudo chmod 100 install.sh; sudo ./install.sh"